name: Check for duplicate envs in Service Catalogue

on:
  workflow_dispatch:
  schedule:
    - cron: "15 7,11,15 * * MON-FRI" # Every weekday at 13:45 UTC

permissions:
  contents: read

jobs:
  duplicate-environments:
    name: Run duplicate environment check
    runs-on: [ self-hosted, hmpps-github-actions-runner ]
    outputs:
      results: ${{ steps.check.outputs.results }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: '3.13'

      - name: Run duplicate environment check
        id: check
        run: |
          rm -f uv.lock
          uv run python utilities/check_duplicate_environments.py
        env:
          SERVICE_CATALOGUE_API_ENDPOINT: ${{ vars.SERVICE_CATALOGUE_API_ENDPOINT }}
          SERVICE_CATALOGUE_API_KEY: ${{ secrets.SERVICE_CATALOGUE_API_KEY }}
          SLACK_ALERTS_CHANNEL: ${{ vars.PROD_SLACK_ALERT_CHANNEL}}

      - id: send-slack 
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        if: steps.check.outputs.results == 'YES' 
        with:
          method: chat.postMessage
          token: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
          payload-file-path: ./slack-message.json
